version: '3.8'

services:
  channels-dvr-player:
    build: 
      context: .
      # Uncomment to build for specific platform
      # platform: linux/amd64  # or linux/arm64
    image: channels-dvr-player:latest
    container_name: channels-dvr-player
    environment:
      - FLASK_DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
    volumes:
      # Mount config directory to persist database and settings
      - ./config:/app/config
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    # Enable host networking for mDNS discovery
    network_mode: host
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7734/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Define volumes for persistence
volumes:
  channels-config:
    driver: local
  channels-logs:
    driver: local
