version: '3.8'

services:
  channels-dvr-player:
    image: kolnsdocker/channels-dvr-player:latest
    container_name: channels-dvr-player
    ports:
      - "7734:7734"  # Map container port 7734 to host port 7734
      # Alternative ports if 7734 is in use:
      # - "8080:7734"  # Access via http://your-server:8080
      # - "3000:7734"  # Access via http://your-server:3000
    environment:
      - FLASK_DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
    volumes:
      # Mount config directory to persist database and settings
      - ./config:/app/config
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7734/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# For servers where you need mDNS discovery (same network as Channels DVR)
# Uncomment the section below and comment out the ports section above
#
# services:
#   channels-dvr-player:
#     image: kolnsdocker/channels-dvr-player:latest
#     container_name: channels-dvr-player
#     network_mode: host  # Use host networking for mDNS discovery
#     environment:
#       - FLASK_DEBUG=false
#       - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-me}
#     volumes:
#       - ./config:/app/config
#       - ./logs:/app/logs
#     restart: unless-stopped

# Optional: Define volumes for persistence
volumes:
  channels-config:
    driver: local
  channels-logs:
    driver: local
